### ISSUE TITLE
Support for Python literals

### ISSUE THREAD

**Issue by MarkusRabe** [mvcisback/py-aiger-bv#22]
We currently have to write "x + atom(wordlen, 1)" to create a circuit that increments x by 1. It should be as simple as "x + 1".

**Comment by mvcisback** [comment]
@MarkusRabe I believe this is already implemented. 

https://github.com/mvcisback/py-aiger-bv/blob/master/aiger_bv/expr.py#L183

Which version of `py-aiger-bv` are you using? Using `2.0.0` yields

```python
In [1]: x = aiger_bv.atom(3, 'x', signed=True)

In [2]: x + 1
Out[2]:
SignedBVExpr(aigbv=AIGBV(aig=aag 9 3 0 3 6
2
4
8
3
18
16
6 2 4
10 6 8
12 7 9
14 3 5
16 11 13
18 7 15
i0 x[0]
i1 x[1]
i2 x[2]
o0 ffa05648-81cb-11ea-b9d0-90e2ba1d0477[0]
o1 ffa05648-81cb-11ea-b9d0-90e2ba1d0477[1]
o2 ffa05648-81cb-11ea-b9d0-90e2ba1d0477[2]
, imap=BundleMap(mapping=pmap({'x': 3})), omap=BundleMap(mapping=pmap({'ffa05648-81cb-11ea-b9d0-90e2ba1d0477': 3})), lmap=BundleMap(mapping=pmap({}))))
```

**Comment by mvcisback** [comment]
@MarkusRabe 

I've also added support for literals in `multiplication` to `2.1.0`.

Closing.
