### ISSUE TITLE
Feature Request 'raise size'

### ISSUE THREAD

**Issue by sjunges** [mvcisback/py-aiger-bv#23]
As discussed:

Given an expression with size n, I would like obtain an expression with the size raised to m >= n without changing the interpretation of the integer represented by the expression.

**Comment by mvcisback** [comment]
Should work in version 4.6.1.

Usage:

```python
import aiger_bv as BV

x = BV,uatom(3, 'x')
y = BV.uatom(5, 'x')
test = x.resize(5) < y
```
