### ISSUE TITLE
dd < 0.6 requirement

### ISSUE THREAD

**Issue by kopeckyf** [mvcisback/py-aiger-bv#26]
Hi @mvcisback and thank you very much for releasing this useful package! 

The install instructions for this package and for your py-mdd package currently require dd < 0.6. Could these be updated to allow for the current dd 0.6?

The changelog for dd 0.6 is available [here](https://github.com/tulip-control/dd/blob/main/CHANGES.md). It does not seem to me that it introduces breaking changes. It now asks for Python 3.11 or above, though.

Best wishes!
Felix

**Comment by mvcisback** [comment]
Sure. I'll look into bumping the dependencies soon.

**Comment by mvcisback** [comment]
@kopeckyf sorry I didn't catch this earlier, but this is py-aiger-bv.

I assume you meant to open up an issue on https://github.com/mvcisback/py-aiger-bdd

**Comment by mvcisback** [comment]
Assuming that's what you meant, the version is now updated in py-aiger-bdd version 3.1.3
